apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flask-app-helm-release-production
  namespace: default
spec:
  valuesFrom:
    - kind: ConfigMap
      name: flask-app-config
      valuesKey: values.yaml
