apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flask-app
  namespace: default
spec:
  valuesFrom:
    - kind: ConfigMap
      name: flask-app-config
      valuesKey: values.yaml
