apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/flask-app
  - ../base/matrix
  - ../base/vless
  - ../base/moviecat
  - ../base/mousebook
  - ../base/mailu
patchesStrategicMerge:
  - flask-app-patch.yaml
  - matrix-patch.yaml
  - vless-patch.yaml
  - mailu-patch.yaml
