apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: moviecat
  namespace: default
spec:
  valuesFrom:
    - kind: ConfigMap
      name: moviecat-config
      valuesKey: values.yaml