apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: flask-app-helm-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://gitlab.com/api/v4/projects/79784810/packages/helm/stable
